<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G7pEHUFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G7pEHUF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G7pEHUF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientProgram' => ['privates', '.errored..service_locator.G7pEHUF.App\\Entity\\ClientPrograms', NULL, 'Cannot autowire service ".service_locator.G7pEHUF": it needs an instance of "App\\Entity\\ClientPrograms" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'clientProgram' => 'App\\Entity\\ClientPrograms',
            'entityManager' => '?',
        ]);
    }
}
