<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KSrkFhKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kSrkFhK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kSrkFhK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientSession' => ['privates', '.errored..service_locator.kSrkFhK.App\\Entity\\ClientSession', NULL, 'Cannot autowire service ".service_locator.kSrkFhK": it needs an instance of "App\\Entity\\ClientSession" but this type has been excluded in "config/services.yaml".'],
        ], [
            'clientSession' => 'App\\Entity\\ClientSession',
        ]);
    }
}
