<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U1B9RHVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u1B9RHV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u1B9RHV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientProgram' => ['privates', '.errored..service_locator.u1B9RHV.App\\Entity\\ClientPrograms', NULL, 'Cannot autowire service ".service_locator.u1B9RHV": it needs an instance of "App\\Entity\\ClientPrograms" but this type has been excluded in "config/services.yaml".'],
        ], [
            'clientProgram' => 'App\\Entity\\ClientPrograms',
        ]);
    }
}
