<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MzOOPVXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MzOOPVX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MzOOPVX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attendance' => ['privates', '.errored..service_locator.MzOOPVX.App\\Entity\\Attendance', NULL, 'Cannot autowire service ".service_locator.MzOOPVX": it needs an instance of "App\\Entity\\Attendance" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'attendance' => 'App\\Entity\\Attendance',
            'entityManager' => '?',
        ]);
    }
}
