<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LIm0GGpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LIm0GGp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LIm0GGp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payment' => ['privates', '.errored..service_locator.LIm0GGp.App\\Entity\\Payments', NULL, 'Cannot autowire service ".service_locator.LIm0GGp": it needs an instance of "App\\Entity\\Payments" but this type has been excluded in "config/services.yaml".'],
        ], [
            'payment' => 'App\\Entity\\Payments',
        ]);
    }
}
