<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttendance2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nI_B5Rm.App\Entity\Attendance' shared service.
     *
     * @return \App\Entity\Attendance
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nI_B5Rm": it needs an instance of "App\\Entity\\Attendance" but this type has been excluded in "config/services.yaml".');
    }
}
