<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientSessionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.L3sGwUl.App\Entity\ClientSession' shared service.
     *
     * @return \App\Entity\ClientSession
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.L3sGwUl": it needs an instance of "App\\Entity\\ClientSession" but this type has been excluded in "config/services.yaml".');
    }
}
