<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrograms2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sLMGPaz.App\Entity\Programs' shared service.
     *
     * @return \App\Entity\Programs
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sLMGPaz": it needs an instance of "App\\Entity\\Programs" but this type has been excluded in "config/services.yaml".');
    }
}
