<?php

namespace ContainerYeU4XTu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrainersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8GWC7wk.App\Entity\Trainers' shared service.
     *
     * @return \App\Entity\Trainers
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8GWC7wk": it needs an instance of "App\\Entity\\Trainers" but this type has been excluded in "config/services.yaml".');
    }
}
