<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NIB5RmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nI_B5Rm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nI_B5Rm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attendance' => ['privates', '.errored..service_locator.nI_B5Rm.App\\Entity\\Attendance', NULL, 'Cannot autowire service ".service_locator.nI_B5Rm": it needs an instance of "App\\Entity\\Attendance" but this type has been excluded in "config/services.yaml".'],
        ], [
            'attendance' => 'App\\Entity\\Attendance',
        ]);
    }
}
