<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I3OaylBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i3OaylB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i3OaylB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'eqipment' => ['privates', '.errored..service_locator.i3OaylB.App\\Entity\\Eqipment', NULL, 'Cannot autowire service ".service_locator.i3OaylB": it needs an instance of "App\\Entity\\Eqipment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'eqipment' => 'App\\Entity\\Eqipment',
        ]);
    }
}
