<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SLMGPazService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sLMGPaz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sLMGPaz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'program' => ['privates', '.errored..service_locator.sLMGPaz.App\\Entity\\Programs', NULL, 'Cannot autowire service ".service_locator.sLMGPaz": it needs an instance of "App\\Entity\\Programs" but this type has been excluded in "config/services.yaml".'],
        ], [
            'program' => 'App\\Entity\\Programs',
        ]);
    }
}
