<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FSFINVgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fSFINVg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fSFINVg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trainer' => ['privates', '.errored..service_locator.fSFINVg.App\\Entity\\Trainers', NULL, 'Cannot autowire service ".service_locator.fSFINVg": it needs an instance of "App\\Entity\\Trainers" but this type has been excluded in "config/services.yaml".'],
        ], [
            'trainer' => 'App\\Entity\\Trainers',
        ]);
    }
}
