<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L3sGwUlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L3sGwUl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L3sGwUl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientSession' => ['privates', '.errored..service_locator.L3sGwUl.App\\Entity\\ClientSession', NULL, 'Cannot autowire service ".service_locator.L3sGwUl": it needs an instance of "App\\Entity\\ClientSession" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'clientSession' => 'App\\Entity\\ClientSession',
            'entityManager' => '?',
        ]);
    }
}
