<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oho6qVBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oho6qVB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oho6qVB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'programsRepository' => ['privates', 'App\\Repository\\ProgramsRepository', 'getProgramsRepositoryService', true],
        ], [
            'programsRepository' => 'App\\Repository\\ProgramsRepository',
        ]);
    }
}
