<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8GWC7wkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8GWC7wk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8GWC7wk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'trainer' => ['privates', '.errored..service_locator.8GWC7wk.App\\Entity\\Trainers', NULL, 'Cannot autowire service ".service_locator.8GWC7wk": it needs an instance of "App\\Entity\\Trainers" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'trainer' => 'App\\Entity\\Trainers',
        ]);
    }
}
