<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DAOKdV0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DAOKdV0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DAOKdV0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientProgramsRepository' => ['privates', 'App\\Repository\\ClientProgramsRepository', 'getClientProgramsRepositoryService', true],
        ], [
            'clientProgramsRepository' => 'App\\Repository\\ClientProgramsRepository',
        ]);
    }
}
