<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YX_NDtfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yX.nDtf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yX.nDtf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'payment' => ['privates', '.errored..service_locator.yX.nDtf.App\\Entity\\Payments', NULL, 'Cannot autowire service ".service_locator.yX.nDtf": it needs an instance of "App\\Entity\\Payments" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'payment' => 'App\\Entity\\Payments',
        ]);
    }
}
