<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientProgramsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G7pEHUF.App\Entity\ClientPrograms' shared service.
     *
     * @return \App\Entity\ClientPrograms
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.G7pEHUF": it needs an instance of "App\\Entity\\ClientPrograms" but this type has been excluded in "config/services.yaml".');
    }
}
