<?php

namespace ContainerGwfDE5L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LIm0GGp.App\Entity\Payments' shared service.
     *
     * @return \App\Entity\Payments
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LIm0GGp": it needs an instance of "App\\Entity\\Payments" but this type has been excluded in "config/services.yaml".');
    }
}
