<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpUz1Nm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpUz1Nm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPpUz1Nm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPpUz1Nm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPpUz1Nm\App_KernelDevDebugContainer([
    'container.build_hash' => 'PpUz1Nm',
    'container.build_id' => '2eb817e3',
    'container.build_time' => 1764767612,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpUz1Nm');
