<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ6Cxj4X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ6Cxj4X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ6Cxj4X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ6Cxj4X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ6Cxj4X\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q6Cxj4X',
    'container.build_id' => '9bdfd7a9',
    'container.build_time' => 1764333317,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ6Cxj4X');
