<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYeU4XTu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYeU4XTu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYeU4XTu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYeU4XTu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYeU4XTu\App_KernelDevDebugContainer([
    'container.build_hash' => 'YeU4XTu',
    'container.build_id' => 'f5caf82c',
    'container.build_time' => 1760794905,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYeU4XTu');
